# Generated by Django 2.0.6 on 2018-06-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=600)),
                ('status', models.BooleanField(default=1)),
                ('not_date', models.DateTimeField(verbose_name='Notification Time')),
            ],
        ),
        migrations.CreateModel(
            name='Lock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1)),
                ('lock_time', models.DateTimeField(verbose_name='Lock Time')),
            ],
        ),
    ]
